// Definition des 10 tiers de robots (cf. GDD section 3.2).
// Tableau lu en cote serveur (validation) et cote client (catalogue shop).

import type { RobotTierStats, RobotType } from '../types/robot.js';

export const ROBOT_TIERS: readonly RobotTierStats[] = [
  {
    type: 'HAND_SHEARS',
    index: 0,
    name: 'Cisaille manuelle',
    baseCost: 0n,
    costGrowth: 1.07,
    baseGrassPerSecond: 0.5,
    cuttingSpeed: 0.5,
    batteryWh: 0,
    autonomySeconds: Number.POSITIVE_INFINITY,
    cuttingWidthCm: 5,
    movementSpeedMs: 0.5,
  },
  {
    type: 'PUSH_MOWER',
    index: 1,
    name: 'Tondeuse a pousser',
    baseCost: 60n,
    costGrowth: 1.15,
    baseGrassPerSecond: 3,
    cuttingSpeed: 1.2,
    batteryWh: 0,
    autonomySeconds: Number.POSITIVE_INFINITY,
    cuttingWidthCm: 30,
    movementSpeedMs: 0.8,
  },
  {
    type: 'GAS_MOWER',
    index: 2,
    name: 'Tondeuse thermique',
    baseCost: 720n,
    costGrowth: 1.14,
    baseGrassPerSecond: 22,
    cuttingSpeed: 2.5,
    batteryWh: 0,
    autonomySeconds: 1800,
    cuttingWidthCm: 45,
    movementSpeedMs: 1.2,
  },
  {
    type: 'ELECTRIC_MOWER',
    index: 3,
    name: 'Tondeuse electrique filaire',
    baseCost: 8_640n,
    costGrowth: 1.13,
    baseGrassPerSecond: 160,
    cuttingSpeed: 3.0,
    batteryWh: 0,
    autonomySeconds: Number.POSITIVE_INFINITY,
    cuttingWidthCm: 50,
    movementSpeedMs: 1.5,
  },
  {
    type: 'ROBOMOW_V1',
    index: 4,
    name: 'Robot autonome v1 (RoboMow)',
    baseCost: 103_680n,
    costGrowth: 1.12,
    baseGrassPerSecond: 1_200,
    cuttingSpeed: 4,
    batteryWh: 200,
    autonomySeconds: 3600,
    cuttingWidthCm: 30,
    movementSpeedMs: 0.5,
  },
  {
    type: 'NAVIBOT',
    index: 5,
    name: 'Robot intelligent (NaviBot)',
    baseCost: 1_244_160n,
    costGrowth: 1.11,
    baseGrassPerSecond: 9_000,
    cuttingSpeed: 6,
    batteryWh: 400,
    autonomySeconds: 7200,
    cuttingWidthCm: 40,
    movementSpeedMs: 1.0,
  },
  {
    type: 'HELIOCUT',
    index: 6,
    name: 'Robot solaire (HelioCut)',
    baseCost: 14_929_920n,
    costGrowth: 1.1,
    baseGrassPerSecond: 67_500,
    cuttingSpeed: 8,
    batteryWh: 600,
    autonomySeconds: Number.POSITIVE_INFINITY,
    cuttingWidthCm: 50,
    movementSpeedMs: 1.2,
  },
  {
    type: 'MEGAMOWER',
    index: 7,
    name: 'Tondeuse industrielle (MegaMower)',
    baseCost: 179_159_040n,
    costGrowth: 1.09,
    baseGrassPerSecond: 506_250,
    cuttingSpeed: 15,
    batteryWh: 2000,
    autonomySeconds: 14_400,
    cuttingWidthCm: 200,
    movementSpeedMs: 2.0,
  },
  {
    type: 'AEROMOW',
    index: 8,
    name: 'Drone-tondeuse aerien (AeroMow)',
    baseCost: 2_149_908_480n,
    costGrowth: 1.08,
    baseGrassPerSecond: 3_800_000,
    cuttingSpeed: 30,
    batteryWh: 5000,
    autonomySeconds: 7200,
    cuttingWidthCm: 100,
    movementSpeedMs: 5.0,
  },
  {
    type: 'NANOSWARM',
    index: 9,
    name: 'Nano-essaim moleculaire (NanoSwarm)',
    baseCost: 25_798_901_760n,
    costGrowth: 1.07,
    baseGrassPerSecond: 28_500_000,
    cuttingSpeed: 100,
    batteryWh: 10_000,
    autonomySeconds: Number.POSITIVE_INFINITY,
    cuttingWidthCm: 1000,
    movementSpeedMs: 10.0,
  },
];

const TIER_BY_TYPE: Record<RobotType, RobotTierStats> = ROBOT_TIERS.reduce(
  (acc, tier) => {
    acc[tier.type] = tier;
    return acc;
  },
  {} as Record<RobotType, RobotTierStats>,
);

export function getTier(type: RobotType): RobotTierStats {
  return TIER_BY_TYPE[type];
}
